name: CI Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: chmod
      run: chmod +x build.sh
    - name: translation
      run: |
        cd Translation\ Editor
        python3 make_translation.py
    - name: make
      run: ./build.sh -l EN
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: compiled
        path: ci/artefacts
